### ISSUE TITLE
Gamma is always nan

### ISSUE THREAD

**Issue by inspirit** [jiuerbujie/omnidirectional_calibration#3]
Hello
i was trying to calibrate my camera using Asymmetric Circles pattern but it seems that algorithm is not able to calculate initial gamma values:
https://github.com/jiuerbujie/omnidirectional_calibration/blob/master/src/omnidir.cpp#L617
here i always get nan that results in crash later when we try to find median value

**Comment by jiuerbujie** [comment]
@inspirit Hi, can you give me your calibration photos, so I can debug. So far I only test it by checkerboard data.

**Comment by inspirit** [comment]
please find extracted frames here: https://www.dropbox.com/s/qv1qiwo3i3q18p8/Archive.zip?dl=0
let em know when u download it so i can delete it.
i can successfully detest circle patter in all this frames using:
```
cv::findCirclesGrid( img, cv::Size(4, 11), point_buf,
                cv::CALIB_CB_ASYMMETRIC_GRID | cv::CALIB_CB_CLUSTERING);
```
corresponding world points will be:
```
for (int i = 0; i < 11; i++)
                for (int j = 0; j < 4; j++)
                    std_obj_pts.push_back(
                                    cv::Point3f(float(i * square_size),
                                                float((2 * j + i % 2) * square_size), 0) + offset);
```

**Comment by jiuerbujie** [comment]
@inspirit  I have download it. I am going see what is wrong. I will remind you when I fix it.

**Comment by jiuerbujie** [comment]
@inspirit Hi, I have tried your data, however I did not meet the error. 

I think the reason maybe the way you input point_buf and std_obj_pts. For convenience, I assume that both of objectPoints(3D) and imagePoints(2D) are type std::vector<Mat> and the Mat is 1xN or Nx1 with type CV_32FC3 and CV_32FC2. Even though all objectPoints are the same in your case, you need to input a vector of Mat. 

I can email you a xml file that I store objectPoints, imagePoints and image_size of your data. You can use it like 
```
    cv::FileStorage fs("corners_circle.xml", cv::FileStorage::READ);
    std::vector<cv::Mat> v_imagePoints, v_patternPoints;
    cv::Size imgSize;
    fs["objectPoints"] >> v_patternPoints;
    fs["imagePoints"] >> v_imagePoints;
    fs["imageSize"] >> imgSize;

    cv::Mat K, D;
    Mat omAll,tAll;
    cv::TermCriteria critia(cv::TermCriteria::COUNT + cv::TermCriteria::EPS, 200, 0.0001);
    Mat xi, idx ;
    int flag = cv::omnidir::CALIB_FIX_SKEW;
    double rms = cv::omnidir::calibrate(v_patternPoints, v_imagePoints, imgSize, K, xi, D, omAll, tAll, flag, critia, idx);
```
BTW, this module is still in developing, if you have any suggestion, please email me :)

**Comment by jiuerbujie** [comment]
@inspirit sorry, I can't find your email address, I upload the xml to here https://drive.google.com/file/d/0B2y35-ODhhqVcFhZb0szNDh5dDA/view?usp=sharing

**Comment by inspirit** [comment]
i see now. it would be much easier if you follow the same interface as cv::calibrate. now it is not that easy to switch. i also noticed that you expect images in ```64F``` not ```32F```. if i provide ```32F``` it will throw exception.
another thing is that if you dont provide ```idx``` argument it will fail to compute any calibration because it uses this argument to filter wrong point matches.

**Comment by jiuerbujie** [comment]
@inspirit OK, I will modify the code and test more. Thank!
