### ISSUE TITLE
stereorectify

### ISSUE THREAD

**Issue by yzpick** [jiuerbujie/omnidirectional_calibration#7]
Hi I am reading this tutorial https://docs.opencv.org/trunk/dd/d12/tutorial_omnidir_calib_main.html and have a question:
you mentioned "Here variable flag indicates the rectify type, only RECTIFY_LONGLATI(recommend) and RECTIFY_PERSPECTIVE make sense." why only RECTIFY_LONGLATI and RECTIFY_PERSPECTIVE make sense?

**Comment by jiuerbujie** [comment]
Hi, @yzpick . That's because only RECTIFY_LONGLATI and RECTIFY_PERSPECTIVE can lead stereo matching on horizontal lines.

**Comment by yzpick** [comment]
I guess my question is why the representation of the images could affect the rectification. I mean when you got the rectifying matrix, you can apply it to whatever the representation of the images to correct the poses and make epipolar line parallel right? if that is right, then you can also rectify_cylindrical or rectify_sphereical; 
for example you use stereoRectify(_R, _T, R1, R2); to get R1 R2 
and then use 
undistortImage(image1.getMat(), undis1, _K1, _D1, xi1, flag, _Knew, newSize, R1);
undistortImage(image2.getMat(), undis2, _K2, _D2, xi2, flag, _Knew, newSize, R2); to correct the pose
specifically, you first get the 3D coordinate and then apply R to the 3D points to get the rectified 3D points:
double _x = iR(0,0)*_xt + iR(0,1)*_yt + iR(0,2)*_wt;
double _y = iR(1,0)*_xt + iR(1,1)*_yt + iR(1,2)*_wt;
double _w = iR(2,0)*_xt + iR(2,1)*_yt + iR(2,2)*_wt;

if such rotation applies to cylindrical images, why cannot it rectify images?
BTW, what is the difference between longlati and spherical coordinate, I found them use same formula

Thanks!

**Comment by jiuerbujie** [comment]
I think correcting pose is not sufficient to make epiploar lines parallel on images. For example, if your representation is fisheye model and pose is corrected, two lines on the left and right camera with the same Y coordinate in 3D space no longer have the same Y coordinate on images, since the distortion is different at every pixel location.

**Comment by yzpick** [comment]
right, I got your point. Thanks for the clarification!
